### ISSUE TITLE
Referencing the Workato global object

### ISSUE THREAD

**Issue by jasonjho** [workato/full-embed-sample#38]
Where is the Workato object imported or initialized? I don't see the Embedding Client js being injected anywhere in the codebase.

**Comment by th0r** [comment]
The Embedding Client script is injected here:
https://github.com/workato/full-embed-sample/blob/bf1610e900e44eafee70841fc07c4f6d049157c0/public/index.html#L16

`VUE_APP_WK_OEM_CLIENT_URL` environment variable must be provided during the build step:
https://github.com/workato/full-embed-sample/blob/bf1610e900e44eafee70841fc07c4f6d049157c0/.env#L4-L5
